name: build_and_deploy

env:
  DOCKERFILE: Dockerfile
  REGISTRY: registry.hub.docker.com
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  TAG0: registry.hub.docker.com/siakhooi/mywise
  REGISTRY1: docker.pkg.github.com
  MYWISE_GITHUB_REGISTRY_USER: ${{ secrets.MYWISE_GITHUB_REGISTRY_USER }}
  MYWISE_GITHUB_REGISTRY_PASSWORD: ${{ secrets.MYWISE_GITHUB_REGISTRY_PASSWORD }}
  TAG1: docker.pkg.github.com/siakhooi/mywise/mywise

on:
  push:
    tags:
    - '*'
jobs:
  build_container_and_push_to_registry:
    name: Build Container and push image to Docker Hub
    runs-on: ubuntu-latest
    container: 
        image: docker:19.03.12-dind
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: set env
        run: echo "MYVERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
      - name: docker build
        run: docker build  -f $DOCKERFILE -t $TAG0:latest -t $TAG0:$MYVERSION -t $TAG1:$MYVERSION .
      - name: docker images
        run: docker images
      - name: Login to Docker Hub
        run: docker login -u $REGISTRY_USER -p "$REGISTRY_PASSWORD" $REGISTRY
      - name: Push to latest
        run: docker push $TAG0:latest
      - name: Push to docker hub
        run: docker push $TAG0:$MYVERSION
      - name: Login to GitHub registry
        run: docker login -u $MYWISE_GITHUB_REGISTRY_USER -p "$MYWISE_GITHUB_REGISTRY_PASSWORD" $REGISTRY1
      - name: Push to github registry
        run: docker push $TAG1:$MYVERSION

